{% set pkg_name = "lz4-c" %}
{% set author = "lz4" %}
{% set name = "lz4" %}
{% set version = "1.8.3" %}
{% set sha256sum = "33af5936ac06536805f9745e0b6d61da606a1f8b4cc5c04dd3cbaca3b9b4fc43" %}
{% set build = 1001 %}

package:
  name: {{ pkg_name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/{{ author }}/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256sum }}
  patches:
    # fullbench build cause "an internal compiler error".
    - patches/0001-Do-not-build-tests-binaries-on-VS-project.patch  # [win]

build:
  skip: True  # [win and vc<14]
  number: {{ build }}
  # https://abi-laboratory.pro/index.php?view=timeline&l=lz4
  run_exports:
    - {{ pin_subpackage(pkg_name, max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
  host:

  run:

test:
  requires:
    - pkg-config  # [unix]

  commands:
    - lz4 -h
    - lz4c -h    # [unix]
    - lz4cat -h  # [unix]
    - unlz4 -h   # [unix]

    - test -f ${PREFIX}/include/lz4.h       # [unix]
    - test -f ${PREFIX}/include/lz4hc.h     # [unix]
    - test -f ${PREFIX}/include/lz4frame.h  # [unix]

    - if not exist %LIBRARY_INC%\\lz4.h exit 1       # [win]
    - if not exist %LIBRARY_INC%\\lz4hc.h exit 1     # [win]
    - if not exist %LIBRARY_INC%\\lz4frame.h exit 1  # [win]

    - test -f ${PREFIX}/lib/liblz4.a      # [unix]
    - test -f ${PREFIX}/lib/liblz4.dylib  # [osx]
    - test -f ${PREFIX}/lib/liblz4.so     # [linux]

    - if not exist %LIBRARY_BIN%\\liblz4.dll exit 1         # [win]
    - if not exist %LIBRARY_LIB%\\liblz4.lib exit 1         # [win]
    - if not exist %LIBRARY_LIB%\\liblz4_static.lib exit 1  # [win]

    - test -f ${PREFIX}/lib/pkgconfig/liblz4.pc  # [unix]
    - pkg-config --cflags --libs liblz4          # [unix]

    - conda inspect linkages -p $PREFIX {{ pkg_name }}  # [unix]
    - conda inspect objects -p $PREFIX {{ pkg_name }}   # [osx]

about:
  home: https://www.lz4.org
  license: BSD 2-clause
  license_file: lib/LICENSE
  summary: Extremely Fast Compression algorithm
  description: |
    LZ4 is lossless compression algorithm, providing compression speed at 400
    MB/s per core (0.16 Bytes/cycle). It features an extremely fast decoder,
    with speed in multiple GB/s per core (0.71 Bytes/cycle). A high compression
    derivative, called LZ4_HC, is available, trading customizable CPU time for
    compression ratio. LZ4 library is provided as open source software using a
    BSD license.

extra:
  recipe-maintainers:
    - rmax
    - wesm
    - xhochy
