appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: dT+2ggeubwIKymW8l1+KQAhbNkozaRq4MRvw/BdTmfUZYrIKS3uEL2kvp8SMsABWRHBRYvwa5muPc1fpxyuRyBmHPDD4FAJTAIyDyTGXvRJMQlNeZNVWjCfdWPE9wlsaT6m6O+dIMNWMt2SuqsLEDAYDvLu91l/dSGyAslqtgvWwRwU0ctUqpjrFT9TYp21kXXg18V+3RIeJ/5KW4XLkBIxIpFfsZaxtq75dKwl7VaSCebR0JB8eHoFrA+zMdM/E9zWGMxQA56gytCcV5pv8TI9HtnIz1WmgS6D+qpRNLXO/XwSRap9MTQF9ydAQpVz9nTlKHwF9IIitFrsjMuL5IihdxKf8USZjXgrb8KAZI+sabTcFUtBLHz4vbcEVSHYWD6BF8STrURQczj6+0B6D6XDVYQGNtQJzd+LFIs8FByo62GbxmTpmkg43aWeiSTG43sHqY6ixMIbiWKxubisqoZInmh62ItuwWZl6aUP9wcxOuYfg+Bav1+CIJ/fvw+o9vP7ET7dU04f9daeRJe0UXdChx5jWrRdHp+4NpqW7pqN48J/aHOwIeuKWUUQ9cu00RXCLLlJiPq1PqX++zLv03g6CHz4HH855wc3PLbrlESqFrkSJXJB0EU7id/Q+6OZpBeg+XJXzUhCBaRLhNzKQDeHLlgIE0sRSZZOrm34w8WA=}
